import type { Metadata } from "next";
import { Inter, Lobster } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const lobster = Lobster({
  subsets: ["latin"],
  weight: ['400'],
  variable: "--font-lobster",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lobster.variable}`}>
        <Navbar />
        {children}
      </body>
    </html >
  );
}
